# 抛出异常
raise Exception('Hello Exception')